### PR TITLE
added: honk feature added

### PR DESCRIPTION
**Pull request by suhasasumukh**
image

I have added a honk button now i can drive around honking :)

### CODE REVIEW

**Comment by shubhxg** [comment]
Yo Thanks, just reduce the sound volume a little bit and also sync up the changes since there one more PR that I just merged!

**Comment by suhasasumukh** [comment]
> Yo Thanks, just reduce the sound volume a little bit and also sync up the changes since there one more PR that I just merged!

sure, btw from where did you download the auido files?

**Comment by shubhxg** [comment]
> > Yo Thanks, just reduce the sound volume a little bit and also sync up the changes since there one more PR that I just merged!
> 
> sure, btw from where did you download the auido files?

[soundsnap](https://www.soundsnap.com/search/audio?query=car+start )

used this website and edited the sounds online to make them more specific to my needs.

**Comment by suhasasumukh** [comment]
@shubhsharma19 it should be good now

**Comment by shubhxg** [comment]
Thankyou! @suhasasumukh 🚗

**Pull request merged**
